SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[usp_trn_GetCokePreAuthTransaction]
	@MERCID NVARCHAR(15),
	@TERMID NVARCHAR(16),
	@TRANSEQ NVARCHAR(12),
	@TRANAUTH NVARCHAR(6)
	AS
    BEGIN
	SELECT TOP 1 MERCID merchantid,TERMID terminalid,BATCHNO,TRANTYPE,TRANAMT,TRANSEQ retrievalrefnum,EDCCHAIN terminalprocesscode,TRANAUTH authidresponse,SETTLDT capturedate,TIMESTAMP transdatetime,ENTRYMODE posentrymode,TRANVOID,CUSTOMER
	FROM dbo.tbl_trn_TransactionCoke WHERE MERCID=@MERCID AND TERMID=@TERMID AND TRANSEQ=@TRANSEQ AND TRANAUTH=@TRANAUTH AND TRANTYPE='A' ORDER BY CREATED desc
    END
GO
