SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[usp_sys_Encrypt] (@Value nvarchar(max),@Data varbinary(max) OUTPUT)
AS
BEGIN
  SET @Data=ENCRYPTBYKEY(KEY_GUID('SymKey_SPS_20150825'),@Value)
  IF @Data IS NULL
  BEGIN
    --OPEN SYMMETRIC KEY sk_EncryptionKey DECRYPTION BY CERTIFICATE ec_EncryptionCert 
	OPEN SYMMETRIC KEY SymKey_SPS_20150825 DECRYPTION BY ASYMMETRIC KEY AsymKey_SPS_20150825
    SET @Data=ENCRYPTBYKEY(KEY_GUID('SymKey_SPS_20150825'),@Value)
	CLOSE SYMMETRIC KEY SymKey_SPS_20150825
  END
END
GO
GRANT EXECUTE ON  [dbo].[usp_sys_Encrypt] TO [WebV4Role]
GO
