SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE PROCEDURE [dbo].[usp_trn_GetCokeLastTransaction]
	@MERCID NVARCHAR(15),
	@TERMID NVARCHAR(16)
	AS
    BEGIN
	SELECT TOP 1 ORGTRACE
	FROM dbo.tbl_trn_TransactionCoke WHERE MERCID=@MERCID AND TERMID=@TERMID ORDER BY CREATED desc
    END
GO
