SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
  CREATE PROCEDURE [dbo].[usp_trn_GetCokeTransaction]
	@MERCID NVARCHAR(15),
	@TERMID NVARCHAR(16),
	@TRANSEQ NVARCHAR(12)
	AS
    BEGIN
	SELECT TOP 1 MERCID merchantid,TERMID terminalid,BATCHNO,TRANTYPE,TRANAMT,TRANSEQ retrievalrefnum,EDCCHAIN termprocessingcode,TRANAUTH authidresponse,SETTLDT capturedate,TIMESTAMP transdatetime,ENTRYMODE posentrymode,TRANRC terminalresponsecode, TRANVOID,CUSTOMER,ORGTRACE
	FROM dbo.tbl_trn_TransactionCoke WHERE MERCID=@MERCID AND TERMID=@TERMID AND TRANSEQ=@TRANSEQ ORDER BY CREATED desc
    END
GO
