SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
 CREATE PROCEDURE [dbo].[usp_trn_InsertCokeTransaction]
    @MERCID NVARCHAR(15),
	@TERMID NVARCHAR(16),
	@BATCHNO INT,
	@BATCHPRDT NCHAR(8),
	@BATCHSRC NVARCHAR(13),
	@TRANTYPE NVARCHAR(1),
	@TRANAMT NVARCHAR(12),
	@TRANSEQ NVARCHAR(12),
	@TRANDT NVARCHAR(4),
	@TRANTM NVARCHAR(4),
	@TRANRC NVARCHAR(2),
	@TRANAUTH NVARCHAR(6),
	@TRANVOID NVARCHAR(1),
	@EDCCHAIN NVARCHAR(6),
	@SETTLDT NVARCHAR(4),
	@TIMESTAMP NVARCHAR(14),
	@PAN NVARCHAR(20),
	@ENTRYMODE NVARCHAR(3),
	@SYSNAME NVARCHAR(9),
    @CREATED INT,
	@CREATEID NVARCHAR(10),
	@CARDTYPE NVARCHAR(1),
	@SRVRNAME NVARCHAR(9),
	@MERCCURR NVARCHAR(3),
	@CUSTOMER NVARCHAR(50),
	@ORGTRACE NVARCHAR(6),
	@SALESORG NVARCHAR(31),
	@MERCNAME NVARCHAR(26)
	AS
    BEGIN
	INSERT INTO dbo.tbl_trn_TransactionCoke
	        ( MERCID ,
	          TERMID ,
	          BATCHNO ,
	          BATCHPRDT ,
	          BATCHSRC ,
	          TRANTYPE ,
	          TRANAMT ,
	          TRANSEQ ,
	          TRANDT ,
	          TRANTM ,
	          TRANRC ,
	          TRANAUTH ,
	          TRANVOID ,
	          EDCCHAIN ,
	          SETTLDT ,
	          TIMESTAMP ,
	          PAN ,
	          ENTRYMODE ,
	          SYSNAME ,
	          CREATED ,
	          CREATEID ,
	          CARDTYPE ,
	          SRVRNAME ,
	          MERCCURR ,
	          CUSTOMER ,
	          ORGTRACE ,
	          SALESORG ,
	          MERCNAME
	        )
	VALUES  (  @MERCID ,
	          @TERMID ,
	          @BATCHNO ,
	          @BATCHPRDT ,
	          @BATCHSRC ,
	          @TRANTYPE ,
	          @TRANAMT ,
	          @TRANSEQ ,
	          @TRANDT ,
	          @TRANTM ,
	          @TRANRC ,
	          @TRANAUTH ,
	          @TRANVOID ,
	          @EDCCHAIN ,
	          @SETTLDT ,
	          @TIMESTAMP ,
	          @PAN ,
	          @ENTRYMODE ,
	          @SYSNAME ,
	          @CREATED ,
	          @CREATEID ,
	          @CARDTYPE ,
	          @SRVRNAME ,
	          @MERCCURR ,
	          @CUSTOMER ,
	          @ORGTRACE ,
	          @SALESORG ,
	          @MERCNAME
	        )
    END
GO
