CREATE TABLE [dbo].[tbl_DeviceCoke]
(
[MERCID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TERMID] [char] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATED] [int] NULL,
[CREATEID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MODIFIED] [int] NULL,
[MODIFYID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SITEID] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INDICATORS] [int] NULL,
[CATEGORY] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURRENCY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESETINTV] [int] NULL,
[FLOORLMT] [int] NULL,
[OPERBEG] [int] NULL,
[OPEREND] [int] NULL,
[RSPFILE] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERMTYPE] [smallint] NULL,
[SURCHARGE] [decimal] (12, 0) NULL,
[TRANAUTH] [int] NULL,
[TRANFAIL] [int] NULL,
[TRANCMPL] [int] NULL,
[LASTTRAN] [int] NULL,
[LASTRESET] [int] NULL,
[TERMNO] [smallint] NULL,
[TERMSERNO] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PPADSERNO] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EDCXMTM] [int] NULL,
[EDCBATCH] [smallint] NULL,
[EDCDBSRC] [smallint] NULL,
[EDCCRSRC] [smallint] NULL,
[PINFORMAT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENWKEY] [smallint] NULL,
[GENWKEYTM] [int] NULL,
[GENWKEYCN] [int] NULL,
[WKEYCTM] [int] NULL,
[WKEYCCNT] [int] NULL,
[MAXAMOUNT] [int] NULL,
[TRANCOUNT] [int] NULL,
[SFDDATE] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERMCAT] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORGCAT0] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORGCAT1] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORGCAT2] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORGCAT3] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORGCAT4] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EPROM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EPROMDT] [date] NULL,
[PROGRAM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROGRAMDT] [date] NULL,
[TABLE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TABLEDT] [date] NULL,
[SVISORPWD] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADMINPWD] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CASHCART] [smallint] NULL,
[LOCKTYPE] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CASHOWNER] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SALESORG] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONENUM] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONECOMP] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INSTALLORG] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTTRACE] [int] NULL,
[USEDEVSCHG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TERMOWNER] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERCENTAGE] [decimal] (10, 0) NULL,
[PERCNTGMIN] [decimal] (12, 0) NULL,
[PERCNTGMAX] [decimal] (12, 0) NULL,
[GENMKEYTM] [int] NULL,
[GENMKEYCN] [int] NULL,
[ALTCATEGORY] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJECTID] [int] NULL,
[PINPADID] [int] NULL,
[VERIFIED] [int] NULL,
[VERIFYID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTTRAN] [int] NULL,
[LANG] [smallint] NULL,
[CONTROLLER] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CFGUPDATE] [smallint] NULL,
[ROUTEGROUP] [nvarchar] (31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VAULTED] [smallint] NULL,
[CERTID] [int] NULL,
[EMVENABLED] [smallint] NULL,
[FULLLOAD] [smallint] NULL,
[CARDREADER] [smallint] NULL,
[PINWKEYLEN] [smallint] NULL,
[MACWKEYLEN] [smallint] NULL,
[SHAREPPAD] [smallint] NULL,
[APPLOADTM] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APPLOADADDR] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[APPLOADACK] [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tbl_DeviceCoke] ADD CONSTRAINT [PK_tbl_DeviceCoke] PRIMARY KEY CLUSTERED  ([MERCID], [TERMID]) ON [PRIMARY]
GO
