CREATE TABLE [dbo].[tbl_rec_TransactionACI]
(
[DateTimeSettlement] [datetime] NOT NULL,
[Currency] [smallint] NOT NULL,
[FilePrefix] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RecordID] [int] NOT NULL,
[RecordType] [smallint] NOT NULL,
[Substate] [smallint] NOT NULL,
[DateTimeAdded] [datetime] NOT NULL,
[IntMsgType] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTranCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgFromAcctType] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgToAcctType] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgCardFIID] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__6C1083C8] DEFAULT (''),
[IntMsgIssuerID] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTranDateTime] [datetime] NOT NULL,
[IntMsgSettlementPostDate] [datetime] NOT NULL,
[IntMsgAcqInterchangeSettlementDate] [datetime] NOT NULL,
[IntMsgIssInterchangeSettlementDate] [datetime] NOT NULL,
[IntMsgTermFIID] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__6D04A801] DEFAULT (''),
[IntMsgTermID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgSeqNum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAN_BINRange] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAN_Last4] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAN_Encrypted] [varbinary] (80) NOT NULL,
[ServiceCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__Servi__6DF8CC3A] DEFAULT (''),
[IntMsgMbrNum] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__6EECF073] DEFAULT (''),
[IntMsgAcqInstID] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgReversalCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgAmount1] [money] NOT NULL,
[IntMsgAmount2] [money] NOT NULL,
[IntMsgOrigDateTime] [datetime] NOT NULL,
[IntMsgTerminalLocationName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__6FE114AC] DEFAULT (''),
[IntMsgTerminalOwnerName] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__70D538E5] DEFAULT (''),
[IntMsgTerminalCity] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__71C95D1E] DEFAULT (''),
[IntMsgTerminalState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__72BD8157] DEFAULT (''),
[IntMsgTerminalCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__73B1A590] DEFAULT (''),
[IntMsgAuthIDResponse] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__IntMs__74A5C9C9] DEFAULT (''),
[ExtMsgType] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ExtMs__7599EE02] DEFAULT (''),
[ExtMsgRespCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ExtMs__768E123B] DEFAULT (''),
[ExtMsgRevCode] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ExtMs__77823674] DEFAULT (''),
[ExtMsgTraceNum] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ExtMs__78765AAD] DEFAULT (''),
[ISO7] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_Tr__ISO7__796A7EE6] DEFAULT (''),
[ISO17] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ISO17__7A5EA31F] DEFAULT (''),
[ISO42] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ISO42__7B52C758] DEFAULT (''),
[ISO48] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ISO48__7C46EB91] DEFAULT (''),
[ISO49] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ISO49__7D3B0FCA] DEFAULT (''),
[ISO50] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ISO50__7E2F3403] DEFAULT (''),
[ISO90] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ISO90__7F23583C] DEFAULT (''),
[ISO95] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ISO95__00177C75] DEFAULT (''),
[ISO100] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__ISO10__010BA0AE] DEFAULT (''),
[TKNB2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__TKNB2__01FFC4E7] DEFAULT (''),
[TKNB3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__TKNB3__02F3E920] DEFAULT (''),
[TKNB4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__TKNB4__03E80D59] DEFAULT (''),
[TKNB5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__TKNB5__04DC3192] DEFAULT (''),
[TKNB6] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__TKNB6__05D055CB] DEFAULT (''),
[FillerField] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tbl_rec_T__Fille__06C47A04] DEFAULT ('')
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tbl_rec_TransactionACI] ADD CONSTRAINT [PK_tbl_rec_TransactionACI] PRIMARY KEY CLUSTERED  ([DateTimeSettlement], [Currency], [FilePrefix], [RecordID]) ON [PRIMARY]
GO
