CREATE TABLE [dbo].[tbl_DeviceCokeSite]
(
[SITEID] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MERCID] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CREATED] [int] NULL,
[CREATEID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MODIFIED] [int] NULL,
[MODIFYID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INDICATORS] [int] NULL,
[ADDRESS1] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESS2] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDRESS3] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CATEGORY] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACT] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACTPHNO] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BRANCHNUM] [int] NULL,
[ACCOUNT] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURRENCY] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEEBRNUM] [int] NULL,
[FEEACCT] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEECURR] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTHEN] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTHTIME] [int] NULL,
[MNGCD] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MNGTIME] [int] NULL,
[CUTOFF] [int] NULL,
[FLOORLMT] [int] NULL,
[OPERBEG] [int] NULL,
[OPEREND] [int] NULL,
[MAXAMOUNT] [int] NULL,
[FCLASS] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YTDTOT] [decimal] (12, 0) NULL,
[YTDFTOT] [decimal] (12, 0) NULL,
[SFDDATE] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITYNAME] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSTAL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRVALPHA2] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DSTFLG] [smallint] NULL,
[DSTDIFF] [decimal] (6, 0) NULL,
[TIMEZONE] [nvarchar] (46) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCLASS1] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANKNAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEEBANKNAME] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BANKINSTNUM] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEEBANKINSTNUM] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMSCONFIG] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tbl_DeviceCokeSite] ADD CONSTRAINT [PK_SITE] PRIMARY KEY CLUSTERED  ([SITEID], [MERCID]) ON [PRIMARY]
GO
