CREATE TABLE [dbo].[tbl_rec_TransactionACIImport]
(
[RowNum] [bigint] NOT NULL,
[Substate] [smallint] NOT NULL,
[RecType] [smallint] NOT NULL,
[IntMsgType] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgProcCode] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgCardFIID] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgIssuerID] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTranDateTime] [char] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgSettlementPostDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgAcqInterchangeSettlementDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgIssInterchangeSettlementDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTermFIID] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTermID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgSeqNum] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PAN] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ServiceCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgMbrNum] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgAcqInstID] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgReversalCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgAmount1] [bigint] NOT NULL,
[IntMsgAmount2] [bigint] NOT NULL,
[IntMsgOrigDateTime] [char] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTerminalLocationName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTerminalOwnerName] [varchar] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTerminalCity] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTerminalState] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgTerminalCountry] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IntMsgAuthIDResponse] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtMsgType] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtCurrentDateTime] [char] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtMsgRespCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtMsgRevCode] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ExtMsgTraceNum] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO7] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO17] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO42] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO48] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO49] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO50] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO90] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO95] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ISO100] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TKNB2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TKNB3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TKNB4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TKNB5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TKNB6] [varchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FillerField] [varchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
