CREATE TABLE [dbo].[tbl_rec_TransactionPulse]
(
[DateTimeSettlement] [datetime] NOT NULL,
[AcquirerBusinessID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RecordSeqNo] [int] NOT NULL,
[Currency] [smallint] NOT NULL,
[IssuerAcquirerFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IssuerBusinessID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExternalTimeStamp] [datetime] NULL,
[SystemBusinessDate] [datetime] NULL,
[AccountID1] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID2] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCode] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcquiringInstID] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcquiringNetworkID] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActionCode] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardAcceptorAddress] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardAcceptorCity] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardAcceptorState] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardAcceptorCountryCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardAcceptorName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardAcceptorID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TerminalID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CardSeqNo] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcquirerCountryCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAN_Last4] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IssuerInstID] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IssuerNetworkID] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocalTimeStamp] [datetime] NULL,
[MCC] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetworkTerminalID] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetrievalRefNum1] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetrievalRefNum2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RetrievalRefNum2Int] [int] NOT NULL,
[ReversalFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemTraceAudit] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountSettlement] [money] NULL,
[SettlementCurrency] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionAmountIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionAmountImpactType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActionValue] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Format8TranType] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalSettlementIndicator] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSEntryMode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSPINCaptureCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmountCount] [int] NULL,
[Amount1Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount1Value] [money] NULL,
[Amount1CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount1ConversionRate] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount1ConversionTimeStamp] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount2Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount2Value] [money] NULL,
[Amount2CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount2ConversionRate] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount2ConversionTimeStamp] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount3Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount3Value] [money] NULL,
[Amount3CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount3ConversionRate] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount3ConversionTimeStamp] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount4Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount4Value] [money] NULL,
[Amount4CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount4ConversionRate] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount4ConversionTimeStamp] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount5Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount5Value] [money] NULL,
[Amount5CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount5ConversionRate] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount5ConversionTimeStamp] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount6Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount6Value] [money] NULL,
[Amount6CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount6ConversionRate] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount6ConversionTimeStamp] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount7Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount7Value] [money] NULL,
[Amount7CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount7ConversionRate] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount7ConversionTimeStamp] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FeeCount] [int] NULL,
[Fee1Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee1Value] [money] NULL,
[Fee1CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee1AmountIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee1AmountImpactType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee2Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee2Value] [money] NULL,
[Fee2CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee2AmountIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee2AmountImpactType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee3Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee3Value] [money] NULL,
[Fee3CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee3AmountIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee3AmountImpactType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee4Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee4Value] [money] NULL,
[Fee4CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee4AmountIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee4AmountImpactType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee5Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee5Value] [money] NULL,
[Fee5CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee5AmountIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee5AmountImpactType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee6Type] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee6Value] [money] NULL,
[Fee6CurrencyCode] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee6AmountIndicator] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee6AmountImpactType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tbl_rec_TransactionPulse] ADD CONSTRAINT [PK_tbl_rec_TransactionPulse] PRIMARY KEY CLUSTERED  ([DateTimeSettlement], [AcquirerBusinessID], [RecordSeqNo], [Currency]) ON [PRIMARY]
GO
