IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NRTTECH\yliu')
CREATE LOGIN [NRTTECH\yliu] FROM WINDOWS
GO
CREATE USER [NRTTECH\yliu] FOR LOGIN [NRTTECH\yliu]
GO
GRANT EXECUTE TO [NRTTECH\yliu]
GRANT VIEW DEFINITION TO [NRTTECH\yliu]
