IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NRTTECH\rzhong')
CREATE LOGIN [NRTTECH\rzhong] FROM WINDOWS
GO
CREATE USER [NRTTECH\rzhong] FOR LOGIN [NRTTECH\rzhong]
GO
GRANT EXECUTE TO [NRTTECH\rzhong]
GRANT VIEW DEFINITION TO [NRTTECH\rzhong]
