IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NRTTECH\vchen')
CREATE LOGIN [NRTTECH\vchen] FROM WINDOWS
GO
CREATE USER [NRTTECH\vchen] FOR LOGIN [NRTTECH\vchen]
GO
GRANT EXECUTE TO [NRTTECH\vchen]
GRANT VIEW DEFINITION TO [NRTTECH\vchen]
