IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NRTTECH\qjiang')
CREATE LOGIN [NRTTECH\qjiang] FROM WINDOWS
GO
CREATE USER [NRTTECH\qjiang] FOR LOGIN [NRTTECH\qjiang]
GO
GRANT EXECUTE TO [NRTTECH\qjiang]
GRANT VIEW DEFINITION TO [NRTTECH\qjiang]
