IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NRTTECH\nliu')
CREATE LOGIN [NRTTECH\nliu] FROM WINDOWS
GO
CREATE USER [NRTTECH\nliu] FOR LOGIN [NRTTECH\nliu]
GO
GRANT EXECUTE TO [NRTTECH\nliu]
GRANT VIEW DEFINITION TO [NRTTECH\nliu]
