IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'NRTTECH\whuo')
CREATE LOGIN [NRTTECH\whuo] FROM WINDOWS
GO
CREATE USER [NRTTECH\whuo] FOR LOGIN [NRTTECH\whuo]
GO
GRANT EXECUTE TO [NRTTECH\whuo]
GRANT VIEW DEFINITION TO [NRTTECH\whuo]
